#ifndef TT3_TOOLS_RESTORE_GLOBAL_HPP
#define TT3_TOOLS_RESTORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(TT3_TOOLS_RESTORE_LIBRARY)
#define TT3_TOOLS_RESTORE_EXPORT Q_DECL_EXPORT
#else
#define TT3_TOOLS_RESTORE_EXPORT Q_DECL_IMPORT
#endif

#endif // TT3_TOOLS_RESTORE_GLOBAL_HPP
